### PR TITLE
made multiple makefiles and modified canonical one

### PR DESCRIPTION
**Pull request by whiteellie**
Issue #10

### CODE REVIEW

**Comment by whiteellie** [comment]
image

**Comment by whiteellie** [comment]
I guess it realized that even though the makefile is different, the targets haven't changed, so it skipped. cool.

**Review by limnoliver — APPROVED** [review]
Woohoo! I much prefer the tidiness of the separate `targets` files -- makes it easier to read and find what I'm looking for.

**Comment by limnoliver** [comment]
I pulled down your changes and reveled in the non-rebuild, too!

**Pull request merged**
